### ISSUE TITLE
Replace hive-hadoop2 with hive for hive connector.name

### ISSUE THREAD

**Issue by victorcouste** [starburstdata/starburst-deploy#4]
In https://github.com/starburstdata/starburst-deploy/tree/main/azure#setting-things-up (must be the same for AWS and GCP), for catalog config, connector.name must be changed from hive-hadoop2 ([410 breaking changes](https://docs.starburst.io/latest/release/release-410-e.html#breaking-changes)) to hive

**Comment by svstaden** [comment]
fixed
